server:
  port: 8001 #会员服务端口号
spring:
  application:
    name: app-xrz-product #服务别名  服务注册到注册中心名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8100/eureka #当前服务注册到eureka服务地址 （服务中心的地址）
    register-with-eureka: true #需要将我的服务注册到eureka上
    fetch-registry: true #需要检索服务